runtime: python39

instance_class: F1

# main:app has been renamed as application:application to ensure compatibility with Amazon Web Services.
# -w 2 sets the number of workers as 2 for compatibility with the F1 instance class.
entrypoint: gunicorn -b :$PORT -w 2 application:application

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto